#e2.1DrawPython.py
from random import*
import turtle
turtle.setup(650, 600, 150, 150)
turtle.penup()
turtle.fd(-100)
turtle.pendown()
turtle.pensize(20)
turtle.pencolor("purple")
turtle.seth(-40)
for i in range(1):
	turtle.circle(40, 60)
	turtle.pencolor("green")
	turtle.circle(20, 70)
	turtle.pencolor("red")
	turtle.circle(-40, 70)
	turtle.pencolor("pink")
	turtle.circle(-40, 70)
	turtle.pencolor("purple")
turtle.circle(100,40)
turtle.pencolor("red")
turtle.circle(50, 90)
turtle.pencolor("orange")
turtle.circle(50, 90)
turtle.pencolor("pink")
turtle.fd(30)
turtle.circle(15, 230)
turtle.pencolor("green")
turtle.circle(20, 60)
turtle.circle(60, 70)
turtle.fd(50 * 1/6)
turtle.pensize(2)
turtle.pencolor("black")
turtle.fd(-2)
turtle.circle(2, 360)
turtle.fd(2)
turtle.pencolor("green")
turtle.fd(8)
turtle.pencolor("red")
turtle.circle(20, 50)
turtle.backward(10)
turtle.circle(-20, 50)
